import ProductImages from "../../../assets/images/productimages";

const productData = [
  {
    id: 1,
    image: ProductImages.product1,
    name: "Kristina Dam Oak Table With White Marble Top",
    icon: null,
    time: null,
    price: 799.55,
    button: false,
    hover: true,
    message: false,
  },
  {
    id: 2,
    image: ProductImages.product2,
    name: "Hay - About A Lounge Chair AAL93",
    icon: null,
    time: null,
    price: 659.55,
    button: true,
    hover: false,
    message: false,
  },
  {
    id: 3,
    image: ProductImages.product3,
    name: "Active Facial Mask and Charcoal Soap",
    icon: null,
    time: null,
    price: 129.55,
    button: false,
    hover: true,
    message: false,
  },
  {
    id: 4,
    image: ProductImages.product4,
    name: "Cocktail Table Walnut | YES",
    icon: null,
    time: null,
    price: 299.99,
    button: false,
    hover: true,
    message: false,
  },
  {
    id: 5,
    image: ProductImages.product5,
    name: "Hay - About A Lounge Chair AAL93",
    icon: null,
    time: null,
    price: 659.55,
    button: false,
    hover: true,
    message: false,
  },
  {
    id: 6,
    image: ProductImages.product6,
    name: "TORY DESK CALENDAR",
    icon: null,
    time: null,
    price: 410.99,
    button: false,
    hover: true,
    message: false,
  },
  {
    id: 7,
    image: ProductImages.product7,
    name: "CH445 Wing Chair on SUITE NY",
    icon: null,
    time: null,
    price: 330.55,
    button: false,
    hover: true,
    message: false,
  },
  {
    id: 8,
    image: ProductImages.productmessage,
    name: "My dragons are misbehaving again. Unbelieveable!",
    icon: ProductImages.productmessageicon,
    time: "5H AGO",
    price: 1,
    button: false,
    hover: false,
    message: true,
  },
];

export default productData;
